[tool.black]
line-length = 88

[tool.pyright]
include = ["src", "tests", "run.py", "setup.py", "make_release.py"]
exclude = ["**/__pycache__", ".venv", "**/migrations/"]
pythonVersion = "3.13"
typeCheckingMode = "basic"
