blank_issues_enabled: false
contact_links:
  - name: ❓ SeriesScape Q&A Discussions
    url: https://github.com/Exonymos/SeriesScape/discussions/categories/q-a
    about: Have a question about setting up or using SeriesScape? Ask the community first!
  - name: 💡 SeriesScape Ideas & Feature Discussions
    url: https://github.com/Exonymos/SeriesScape/discussions/categories/ideas
    about: Share and discuss new feature ideas with the community.
  - name: 💬 SeriesScape General Chat
    url: https://github.com/Exonymos/SeriesScape/discussions/categories/general
    about: For other general discussions related to SeriesScape.
